version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    volumes_from:
      - bundle
    links:
      - db
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=db
  db:
    image: mysql:5.7
    ports:
      - "3310:3306" # sequelproを使う人向け
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
  bundle:
    image: busybox
    volumes:
      - /bundle
